name: Firebase
on:
  push:
    branches:
    - master
jobs:
  main:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
       node-version: ${{ matrix.node-version }}    
    - name: Install TypeScript
      run: |
           npm install -g concurrently && npm install -g typescript --force
    - name: install libraries
      run: cd functions
           npm install
      working-directory: ${{env.working-directory}}
    - name: install firebase
      run: npm i firebase-tools -g
    - name: Check out code
      uses: actions/checkout@master          
    - name: Deploy to Firebase
      uses: w9jds/firebase-action@master
      with:
          args: deploy --only functions
      env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
          FIREBASE_PROJECT: bitbadges
