name: Firebase
on:
  push:
    branches:
    - master
jobs:
  main:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
       node-version: ${{ matrix.node-version }}    
    - name: Install TypeScript
      run: |
          npm install typescript -g
    - name: Check out code
      uses: actions/checkout@master          
    - name: Deploy to Firebase
      uses: BIGG-Kaymo/deploy-firebase-functions@v1.0.1
      env:
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
